### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by AleksiKopponen** [niilopoutanen/UnityTetris#1]
Kun pelasin peliäsi nii minulla näkyi sekuntti kellossa aivan liikaa desimaaleja :OOOOOOOOOO 😨 😨 😨 😨 😨 😨 😨 

ainiijjoo laitaks mulle 50€ tilille mobilepay kautta?

**Comment by niilopoutanen** [comment]
Asia selvä, homma korjattu. 50€ jää nyt kuitenkin valitettavasti saamatta.
