### ISSUE TITLE
Game over and achievements don't work 

### ISSUE THREAD

**Issue by Muzek85** [niilopoutanen/UnityTetris#2]
**Describe the bug**
Game over doesn't work same as achievements. 

**To Reproduce**

**Expected behavior**
Describe what you expected to happen instead of the error.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Version*
 - Version [e.g. 1.0]

**Additional context**
So the game doesn't recognize when you've come to the top of the box and doesn't end in a game over. Also doesn't recognize achievements when they are achived.

**Comment by niilopoutanen** [comment]
Thanks for feedback! 
I haven't encountered this issue, but i released a newer version that should eliminate all possibilities for such error to happen.
If you encounter this issue again please report it.
